"""add, roles to user

Revision ID: 8530f562282f
Revises: cecc8248573e
Create Date: 2025-01-14 21:35:38.446163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8530f562282f'
down_revision: Union[str, None] = 'cecc8248573e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('role', sa.VARCHAR(), nullable=False, server_default='user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
