"""add, new tag and booktag tables

Revision ID: c81c9a5489bd
Revises: 9e0c64c03b50
Create Date: 2025-01-16 20:04:14.100126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81c9a5489bd'
down_revision: Union[str, None] = '9e0c64c03b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktag',
    sa.Column('book_uid', sa.UUID(), nullable=False, foreign_key='book.uid'),
    sa.Column('tag_uid', sa.UUID(), nullable=False, foreign_key='tag.uid'),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid')
    )
    op.create_table('tag',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('booktag')
    # ### end Alembic commands ###
